### ISSUE TITLE
Issues with models and performance after 30 minutes of play time.

### ISSUE THREAD

**Issue by Commander-DusK** [fred41/tbbmalloc_arma#5]
As you can see from the screenshots the models change into extremely low quality ones and mine and other player models t-posing after just 30 minutes of playtime and comes with a huge performance hit once these models show up (40fps to 3fps). I have tested on both singleplayer and multiplayer ArmA 3 Ver. 1.58.135656. Temporary fix is to of coarse switch to another malloc. PC is Win10 16GB RAM. I have also included the malloc log if that helps.
![20160424191113_1](https://cloud.githubusercontent.com/assets/5379197/14766655/e6747fb4-0a51-11e6-94a4-e5bddb7a3f42.jpg)
![20160424191242_1](https://cloud.githubusercontent.com/assets/5379197/14766656/e6780530-0a51-11e6-9d6d-40906fe64634.jpg)
[malloc_05f8forgithub.txt](https://github.com/fred41/tbbmalloc_arma/files/233366/malloc_05f8forgithub.txt)

**Comment by fred41** [comment]
Please notice, this project is closed since months, as you can read in 'readme.md'.
I will make an exception and answer your question here and now. 

According to your log-file, there are no anomalies in memory allocation,
hence i see no reason to assume an allocator problem.
Rather i would guess there is some sort of memory leak in latest arma, that fills the limited address space (in your case < 4GB), forcing everything (including allocator) to reduce resource consumption.

BTW:
Your setup isn't using 'large pages' (the main advantage of this allocator) and hence you could even use every other allocator. Please read the readme.md and my related post in BI's forum how to set it up correctly.

Since this project is closed already, i will close this issue now.
